EXECUTE SDO_TOPO.CREATE_TOPOLOGY('CITY_DATA', 0.00005);--oracle
CREATE TABLE "DEBEZIUM"."CITY_DATA_FACE$" (	
     "FACE_ID" NUMBER PRIMARY KEY，
	 "BOUNDARY_EDGE_ID" NUMBER, 
	 "ISLAND_EDGE_ID_LIST" json , 
	 "ISLAND_NODE_ID_LIST" json , 
	 "MBR_GEOMETRY" json 
     ）; --openaguss
INSERT INTO city_data_face$ values (
    -1, 
    NULL,
    SDO_LIST_TYPE(-1, -2, 4, 6),
    SDO_LIST_TYPE(),
    NULL);
commit;--oracle
INSERT INTO city_data_face$ VALUES (
    3, 
    19, 
    SDO_LIST_TYPE(), 
    SDO_LIST_TYPE(),
    SDO_GEOMETRY(2003, NULL, NULL, SDO_ELEM_INFO_ARRAY(1,1003,3),SDO_ORDINATE_ARRAY(9,14, 21,22))
);
commit;--oracle
INSERT INTO city_data_face$ VALUES(
    4, 
    17,
    SDO_LIST_TYPE(),
    SDO_LIST_TYPE(),
    SDO_GEOMETRY(2003, NULL, NULL, SDO_ELEM_INFO_ARRAY(1,1003,3),SDO_ORDINATE_ARRAY(21,14, 35,22))
);
commit;--oracle
INSERT INTO city_data_face$ VALUES (
    6,
    20,
    SDO_LIST_TYPE(), 
    SDO_LIST_TYPE(),
    SDO_GEOMETRY(2003, NULL, NULL, SDO_ELEM_INFO_ARRAY(1,1003,3),SDO_ORDINATE_ARRAY(9,6, 21,14))
);
commit;--oracle
INSERT INTO city_data_face$ VALUES (
    7, 
    10, 
    SDO_LIST_TYPE(), 
    SDO_LIST_TYPE(),
    SDO_GEOMETRY(2003, NULL, NULL, SDO_ELEM_INFO_ARRAY(1,1003,3),SDO_ORDINATE_ARRAY(21,6, 35,14))
);
commit;--oracle
CREATE TABLE "DEBEZIUM"."CITY_DATA_RELATION$" ( 
    "TG_LAYER_ID" NUMBER, 
    "TG_ID" NUMBER, 
    "TOPO_ID" NUMBER, 
    "TOPO_TYPE" NUMBER, 
    "TOPO_ATTRIBUTE" VARCHAR2(100), 
     CONSTRAINT "CITY_DATAREL_PK" PRIMARY KEY ("TG_LAYER_ID", "TG_ID", "TOPO_ID", "TOPO_TYPE")
);
commit;--opengauss
CREATE TABLE "DEBEZIUM"."LAND_PARCELS" (    
    "FEATURE_NAME" VARCHAR2(30), 
    "FEATURE" json, 
    PRIMARY KEY ("FEATURE_NAME")
);
commit;--opengauss
CREATE TABLE "DEBEZIUM"."CITY_DATA_HISTORY$" 
   (    "TOPO_TX_ID" NUMBER, 
    "TOPO_SEQUENCE" NUMBER, 
    "TOPOLOGY" VARCHAR2(20), 
    "TOPO_ID" NUMBER, 
    "TOPO_TYPE" NUMBER, 
    "TOPO_OP" VARCHAR2(3), 
    "PARENT_ID" NUMBER, 
     CONSTRAINT "CITY_DATAHIS_PK" PRIMARY KEY ("TOPO_TX_ID", "TOPO_SEQUENCE")
    );--opengauss